# NumPy Practice Coding Questions

#### Question 1
Create a 1D NumPy array containing the numbers from 0 to 9.

In [1]:
import numpy as np

In [2]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Question 2
Create a 3x3 NumPy array filled with all ones.

In [3]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### Question 3
Create a NumPy array of 10 fives.

In [4]:
5 * np.ones(10)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Question 4
Create a NumPy array containing the even numbers from 10 to 30.

In [5]:
np.arange(10, 31, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

#### Question 5
Create a 3x3 identity matrix.

In [6]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Question 6
Generate a random number between 0 and 1 using NumPy.

In [7]:
np.random.rand()

0.7456604720095025

#### Question 7
Generate an array of 25 random numbers sampled from a standard normal distribution.

In [8]:
# Important
np.random.randn(25)

array([-0.0223769 , -0.74222247,  0.19793455,  0.76605366,  0.40479965,
        0.26327205,  1.06927649, -1.12197016,  1.3200475 ,  0.65731045,
        0.18813085, -0.83289289, -1.38544064,  1.66192746, -2.44734139,
       -0.31621936,  0.76121693, -0.96092029, -0.23318176,  1.11262421,
       -0.75329467, -0.19607533,  0.62589997,  0.04855104,  0.62945893])

#### Question 8
Create a NumPy array of 20 linearly spaced points between 0 and 1.

In [9]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

#### Question 9
Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.

In [10]:
# Review
np.diag([1, 2, 3, 4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [11]:
np.diag(np.arange(1, 5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### Question 10
Create a 5x5 matrix with random values and find the minimum and maximum values.

In [12]:
arr = np.random.randint(1, 10, (5, 5))
print(arr)
print(arr.max())
print(arr.min())

[[2 3 4 4 1]
 [8 7 3 7 2]
 [5 4 8 3 1]
 [8 5 9 2 4]
 [6 6 9 6 5]]
9
1


#### Question 11
Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).

In [13]:
arr_1 = np.random.randint(1, 10, (5, 3))
arr_2 = np.random.randint(1, 10, (3, 2))
np.dot(arr_1, arr_2)

array([[101,  43],
       [128,  76],
       [ 91,  65],
       [141,  81],
       [ 44,  28]])

#### Question 12
Create a 8x8 matrix and fill it with a checkerboard pattern of 1s and 0s.

In [14]:
arr = np.zeros((8, 8), dtype=int)
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### Question 13
Create a sorted array of 10 random numbers.

In [15]:
arr = np.random.rand(10)
np.sort(arr)

array([0.10449016, 0.11669376, 0.22206687, 0.41457278, 0.44235076,
       0.57413655, 0.66073039, 0.79731545, 0.80826449, 0.96661682])

#### Question 14
Find the sum of all the values in a 3x3 matrix.

In [16]:
arr = np.random.randint(1, 10, (3, 3))
np.sum(arr)

32

#### Question 15
Find the standard deviation of a 1D array of numbers from 1 to 10.

In [17]:
np.std(np.arange(1, 11))

2.8722813232690143

#### Question 16
Create a random 3x3x3 array and find the sum of all elements.

In [18]:
arr = np.random.randint(1, 10, (3, 3, 3))
np.sum(arr)

127

#### Question 17
Create a random vector of size 30 and find the mean value.

In [19]:
arr = np.random.rand(30)
arr.mean()

0.5513917053549838

#### Question 18
Subtract the mean of each row of a matrix (from each corresponding row).

In [20]:
arr = np.random.randint(1, 10, (3, 3))
print(arr)
mean = arr.mean(axis=1, keepdims=True) # important
print(mean)
arr - mean

[[2 6 8]
 [7 1 2]
 [4 5 6]]
[[5.33333333]
 [3.33333333]
 [5.        ]]


array([[-3.33333333,  0.66666667,  2.66666667],
       [ 3.66666667, -2.33333333, -1.33333333],
       [-1.        ,  0.        ,  1.        ]])

#### Question 19
Create a 5x5 matrix of random floats from 0 to 1 and sort by the 2nd column.

In [21]:
arr = np.random.rand(5, 5)
arr[arr[:, 1].argsort()] # important!!

array([[0.33768574, 0.11048965, 0.65543029, 0.33391776, 0.55901139],
       [0.15485861, 0.13994423, 0.81915043, 0.72407536, 0.22518828],
       [0.27865452, 0.59173989, 0.14153569, 0.53043769, 0.26823932],
       [0.48315   , 0.69668476, 0.2332964 , 0.93718636, 0.87874305],
       [0.65997775, 0.79447816, 0.86363821, 0.46136317, 0.37096335]])

#### Question 20
Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates.

In [30]:
np.arctan2?

In [29]:
cartesian_coords = np.random.random((10, 2))
print(cartesian_coords)
# to do
polar_coords = np.zeros_like(cartesian_coords)
polar_coords[:, 0] = np.sqrt(cartesian_coords[:, 0]**2 + cartesian_coords[:, 1]**2)
polar_coords[:, 1] = np.arctan2(cartesian_coords[:, 1], cartesian_coords[:, 0])
print(polar_coords)

X,Y = cartesian_coords[:,0], cartesian_coords[:,1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y,X)
print(R, T)

[[4.92287727e-04 2.07875433e-01]
 [8.06047646e-01 8.63667059e-01]
 [5.85607622e-01 8.68651853e-01]
 [2.78860917e-01 8.63392358e-01]
 [3.36971465e-01 8.99300664e-01]
 [4.27301205e-01 9.15211171e-01]
 [8.27132040e-01 5.86681955e-01]
 [7.76508357e-01 9.38147377e-01]
 [1.54816292e-01 3.33942520e-01]
 [5.23572679e-01 5.56241467e-01]]
[[0.20787602 1.56842815]
 [1.18136937 0.81989301]
 [1.04761268 0.9776261 ]
 [0.90730908 1.25838996]
 [0.96036006 1.21228528]
 [1.01004842 1.13398735]
 [1.01407255 0.61693809]
 [1.21782007 0.87938948]
 [0.36808381 1.13668904]
 [0.76389327 0.81564302]]
[0.20787602 1.18136937 1.04761268 0.90730908 0.96036006 1.01004842
 1.01407255 1.21782007 0.36808381 0.76389327] [1.56842815 0.81989301 0.9776261  1.25838996 1.21228528 1.13398735
 0.61693809 0.87938948 1.13668904 0.81564302]


#### Question 21
Find the maximum value in each row of a NumPy 2D array.

In [23]:
arr = np.random.randint(0, 10, (3, 3))
print(arr)
np.max(arr, axis=1)

[[9 6 0]
 [1 5 0]
 [6 7 4]]


array([9, 5, 7])

#### Question 23
Create a 5x5 matrix with row values ranging from 0 to 4, using the tile function.

In [34]:
np.tile(np.arange(0, 5), (5, 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### Question 24
Create a linearly spaced vector of size 10 with values ranging from 0 to 1, but with both excluded.

In [35]:
np.linspace(0, 1, 12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### Question 25
Create two random arrays, A and B, and check if they are equal.

In [37]:
A = np.random.random((5, 5))
B = np.random.random((5, 5))
A == B

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [38]:
np.allclose(A,B) # important

False

#### Question 26
Create a random 10x2 matrix representing cartesian coordinates and convert them to polar coordinates.

In [39]:
cartesian_coor = np.random.random((10, 2))
X, Y = cartesian_coor[:, 0], cartesian_coor[:, 1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(X, Y)
R, T

(array([0.94263273, 0.64146805, 0.88057216, 0.41098627, 1.3174488 ,
        0.90471737, 0.84493169, 0.76776995, 1.01818557, 1.31046165]),
 array([0.4375385 , 1.38544149, 1.13301843, 1.47488978, 0.83989868,
        0.25319632, 0.52954184, 0.31958579, 0.24643157, 0.83901662]))

#### Question 27
Create a large vector Z (more than 100 values) and compute Z to the power of 3 using 2 different methods.

In [42]:
Z = np.random.random(101)
print(Z ** 3)
np.power(Z, 3)

[2.92960734e-02 2.56745582e-01 5.22973710e-01 8.77773885e-01
 7.17959469e-02 5.85438966e-02 8.84384070e-04 2.09402039e-03
 5.80225276e-01 2.40012077e-01 5.37395660e-01 5.95717857e-04
 5.45923954e-01 4.37946605e-02 2.52651608e-01 3.71053438e-01
 6.68648165e-02 4.56571981e-01 4.25169105e-01 3.85013541e-01
 4.39124917e-02 6.31054402e-01 1.89110413e-03 4.10340529e-01
 2.99054766e-02 9.10420895e-03 4.06401581e-02 5.50948026e-01
 2.94813471e-04 7.76590848e-01 6.88576283e-01 2.65555785e-02
 5.78487132e-01 3.83921926e-01 1.88491538e-02 1.54633564e-02
 1.44513879e-07 1.87150437e-05 9.22514582e-03 5.81202086e-03
 6.49927282e-01 2.02962395e-01 5.30524133e-04 1.32795234e-01
 3.53991894e-01 4.19007571e-01 3.45185493e-01 8.59925130e-03
 1.06213854e-02 3.15501700e-01 4.77550104e-02 2.89056629e-02
 3.93592001e-02 5.47152005e-02 5.99934585e-01 5.25266451e-01
 7.47497084e-04 7.13513883e-01 1.42741920e-01 2.33411505e-02
 8.77476251e-01 6.58831390e-03 5.64560898e-01 1.26736388e-01
 9.05118890e-01 8.947514

array([2.92960734e-02, 2.56745582e-01, 5.22973710e-01, 8.77773885e-01,
       7.17959469e-02, 5.85438966e-02, 8.84384070e-04, 2.09402039e-03,
       5.80225276e-01, 2.40012077e-01, 5.37395660e-01, 5.95717857e-04,
       5.45923954e-01, 4.37946605e-02, 2.52651608e-01, 3.71053438e-01,
       6.68648165e-02, 4.56571981e-01, 4.25169105e-01, 3.85013541e-01,
       4.39124917e-02, 6.31054402e-01, 1.89110413e-03, 4.10340529e-01,
       2.99054766e-02, 9.10420895e-03, 4.06401581e-02, 5.50948026e-01,
       2.94813471e-04, 7.76590848e-01, 6.88576283e-01, 2.65555785e-02,
       5.78487132e-01, 3.83921926e-01, 1.88491538e-02, 1.54633564e-02,
       1.44513879e-07, 1.87150437e-05, 9.22514582e-03, 5.81202086e-03,
       6.49927282e-01, 2.02962395e-01, 5.30524133e-04, 1.32795234e-01,
       3.53991894e-01, 4.19007571e-01, 3.45185493e-01, 8.59925130e-03,
       1.06213854e-02, 3.15501700e-01, 4.77550104e-02, 2.89056629e-02,
       3.93592001e-02, 5.47152005e-02, 5.99934585e-01, 5.25266451e-01,
      

#### Question 28
Consider two arrays A and B, write code that will compare A and B element-wise.

In [43]:
A = np.random.random((5, 5))
B = np.random.random((5, 5))
A == B

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [44]:
np.equal(A, B)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

#### Question 29
Define two arrays and write code to find the common values between them.

In [46]:
A = np.array([1,2,3,4,5])
B = np.array([4,5,6,7,8])
np.intersect1d(A, B)

array([4, 5])

#### Question 30
Consider the following NumPy array, representing the annual average temperatures (in degrees Celsius) for 12 cities from January to December. Write the NumPy code to extract the temperatures for the first quarter (January to March) for City 5. Explain your indexing approach.

In [24]:
temperatures = np.array([
    [5, 7, 10, 15, 20, 25, 30, 29, 24, 18, 12, 6],   # City 1
    [6, 9, 11, 16, 21, 26, 31, 30, 25, 19, 13, 7],   # City 2
    [8, 10, 13, 18, 23, 28, 33, 32, 27, 21, 15, 9],  # City 3
    [7, 9, 12, 17, 22, 27, 32, 31, 26, 20, 14, 8],   # City 4
    [5, 8, 11, 16, 21, 26, 31, 30, 25, 19, 13, 7],   # City 5
    [10, 12, 15, 20, 25, 30, 35, 34, 29, 23, 17, 11],# City 6
    [11, 13, 16, 21, 26, 31, 36, 35, 30, 24, 18, 12],# City 7
    [4, 7, 9, 14, 19, 24, 29, 28, 23, 17, 11, 5],    # City 8
    [6, 8, 11, 15, 20, 25, 30, 29, 24, 18, 12, 6],   # City 9
    [9, 11, 14, 19, 24, 29, 34, 33, 28, 22, 16, 10], # City 10
    [3, 5, 8, 13, 18, 23, 28, 27, 22, 16, 10, 4],    # City 11
    [4, 6, 8, 13, 18, 23, 28, 27, 22, 16, 10, 5]     # City 12
])

In [58]:
# In Numpy, array index starts at 0, therefore, index 4 is City 5
# And we only need to extract the temeratures for 3 months (1 - 3)
# Use slice "up to but not include" [:3] to get the months at
# the index of 0, 1, 2 in the 2nd dimension
temperatures[4][:3] # Use the index of a 2D array

array([ 5,  8, 11])

In [59]:
# easier solution
temperatures[4, :3] # fancy index of numpy

array([ 5,  8, 11])

#### Question 31
Using boolean indexing, select all the cities that have an average temperature above 20 degrees Celsius in July. Describe the steps you take to achieve this.

In [62]:
"""
select all the cities that have an average temperature above 20 degrees Celsius in July,
it means we need to go through all rows, therefore, we use [:,] for rows.
And we only need to the July temperature is in the 7th column of each row, whose index is 6
So the final slice we use is [:, 6]
To create a boolean value we use comparsion "temperatures[:, 6] > 20" as a mask
Now we can put the mask in the index area temperatures[temperatures[:, 6] > 20]
"""
temperatures[temperatures[:, 6] > 20] # use the mask of numpy

array([[ 5,  7, 10, 15, 20, 25, 30, 29, 24, 18, 12,  6],
       [ 6,  9, 11, 16, 21, 26, 31, 30, 25, 19, 13,  7],
       [ 8, 10, 13, 18, 23, 28, 33, 32, 27, 21, 15,  9],
       [ 7,  9, 12, 17, 22, 27, 32, 31, 26, 20, 14,  8],
       [ 5,  8, 11, 16, 21, 26, 31, 30, 25, 19, 13,  7],
       [10, 12, 15, 20, 25, 30, 35, 34, 29, 23, 17, 11],
       [11, 13, 16, 21, 26, 31, 36, 35, 30, 24, 18, 12],
       [ 4,  7,  9, 14, 19, 24, 29, 28, 23, 17, 11,  5],
       [ 6,  8, 11, 15, 20, 25, 30, 29, 24, 18, 12,  6],
       [ 9, 11, 14, 19, 24, 29, 34, 33, 28, 22, 16, 10],
       [ 3,  5,  8, 13, 18, 23, 28, 27, 22, 16, 10,  4],
       [ 4,  6,  8, 13, 18, 23, 28, 27, 22, 16, 10,  5]])

#### Question 32
City 8 is planning an event and needs to know their average temperature for the months where City 3's temperature is below 15 degrees Celsius. Write the NumPy code to find this information and explain the logic behind your solution.

In [68]:
# the months where City 3's temperature is below 15 degree
# temperatures[2, :] < 15

# For city 8, the outer index is temperatures[7, columns]
# columns = temperatures[2, :] < 15
# For the total average temperature, we can use np.mean()
# or ndarray.mean()
temperatures[7, temperatures[2, :] < 15].mean()

6.25

In [65]:
city_3_cold_months = temperatures[2] < 15
city_8_temps_during_city_3_cold = temperatures[7, city_3_cold_months]
average_temp_city_8 = np.mean(city_8_temps_during_city_3_cold)
print("Average temperature for City 8 during City 3's cold months:", average_temp_city_8)

Average temperature for City 8 during City 3's cold months: 6.25
