Please answer the following questions about Numpy array attributes. These questions delve into the various attributes of numpy arrays, which provide information about the array's properties and memory layout. You may have to look further into the notes for this week or documentation to find some of the answers. Give each answer in a separate cell below:

1. What attribute of a numpy array gives its dimensions?
2. How can you determine the total number of elements in a numpy array?
3. Which attribute provides the shape of a numpy array as a tuple?
4. What does the `dtype` attribute of a numpy array represent?
5. How can you find out the number of dimensions of a numpy array?
6. Which attribute gives the size in bytes of each element of the array?
7. What is the difference between the `size` and `itemsize` attributes of a numpy array?
8. How can you determine the total bytes consumed by the elements of a numpy array?
9. What does the `nbytes` attribute of a numpy array represent?
10. Which attribute can be used to transpose the dimensions of a numpy array?
11. How can you get the memory address of the first byte in the array's data?
12. What does the `strides` attribute of a numpy array indicate?
13. How can you check if the elements in a numpy array are in contiguous memory?
14. What is the significance of the `base` attribute in a numpy array?
15. How can you determine if the memory of a numpy array is writeable?
16. What does the `flags` attribute of a numpy array provide?
17. How can you check if a numpy array is a view of another array?
18. Which attribute gives information about the memory layout of the array?
19. How can you determine the reference count of the array's data?
20. What does the `T` attribute of a numpy array represent?



1. What attribute of a numpy array gives its dimensions?

In [1]:
import numpy as np

a = np.arange(0, 10, 2)
a.ndim

1

2. How can you determine the total number of elements in a numpy array?

In [ ]:
a.size

5

3. Which attribute provides the shape of a numpy array as a tuple?


In [ ]:
a.shape

(5,)

4. What does the `dtype` attribute of a numpy array represent?

In [ ]:
# represent the data type of the elements in the ndarray
a.dtype

dtype('int64')

5. How can you find out the number of dimensions of a numpy array?


In [ ]:
a.ndim

1

6. Which attribute gives the size in bytes of each element of the array?

In [ ]:
a.itemsize # important

8

7. What is the difference between the `size` and `itemsize` attributes of a numpy array?

In [ ]:
# "size" gives you the number of elemens in a numpy array
# "itemsize" gives you the size in bytes of each element of the array

8. How can you determine the total bytes consumed by the elements of a numpy array?

In [ ]:
a.nbytes # important

40

`size` gives the total number of elements in an numpy array,

`itemsize` gives how many bytes are occupied by an element in an ndarray

`nbytes` gives the total bytes of memory occupied by a ndarray

9. What does the `nbytes` attribute of a numpy array represent?


In [ ]:
# a.nbytes gives the total bytes consumed by a numpy array

40

10. Which attribute can be used to transpose the dimensions of a numpy array?

In [4]:
array = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
]
array = np.array(array)
array.T # importatn

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [9]:
# .transpose() is more powerful when you need to customize the dimension rearrangement.
array.transpose() # method

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

11. How can you get the memory address of the first byte in the array's data?

In [ ]:
address = a.data # important
print(address)

12. What does the `strides` attribute of a numpy array indicate?

In [10]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]], dtype=np.int32)
print(arr.itemsize)
print(arr.strides)  # Tuple specifying the memory layout along each axis.

4
(12, 4)


In [11]:
# The strides attribute of a numpy array indicates the number of bytes that
# should be skipped in memory to move to the next element.
print(a)
a.strides

[0 2 4 6 8]


(8,)

13. How can you check if the elements in a numpy array are in contiguous memory?

In [ ]:
# The flags attribute's C_CONTIGUOUS (or C) and
# F_CONTIGUOUS (or F) values can be checked to see if the elements in a numpy array are in contiguous memory.
a.flags['C_CONTIGUOUS']

True

In [21]:
a.flags.c_contiguous

True

In [ ]:
a.flags['F_CONTIGUOUS']

True

In [12]:
# Create a sample NumPy array
ndarray = np.array([1, 2, 3])

# Check the flags
var_1 = ndarray.flags['C_CONTIGUOUS']
var_2 = ndarray.flags['F_CONTIGUOUS']

# Define the text
text = "What is the difference between C_CONTIGUOUS and F_CONTIGUOUS?"

# Answer the question
answer = "The difference between C_CONTIGUOUS and F_CONTIGUOUS is in the memory layout of a NumPy array:\n"
answer += f"C_CONTIGUOUS (C order) means that the data is stored in a row-major (C-style) memory layout, where rows are contiguous.\n"
answer += f"F_CONTIGUOUS (Fortran order) means that the data is stored in a column-major (Fortran-style) memory layout, where columns are contiguous."

print(answer)

The difference between C_CONTIGUOUS and F_CONTIGUOUS is in the memory layout of a NumPy array:
C_CONTIGUOUS (C order) means that the data is stored in a row-major (C-style) memory layout, where rows are contiguous.
F_CONTIGUOUS (Fortran order) means that the data is stored in a column-major (Fortran-style) memory layout, where columns are contiguous.


14. What is the significance of the `base` attribute in a numpy array?


In [ ]:
# The base attribute in a numpy array contains the base object if
# the array is a view (i.e., derived from another array), otherwise it is None.
print(a.base)
b = a[:]
b.base

None


array([0, 2, 4, 6, 8])

Base object if memory is from some other object.

Examples
--------
The base of an array that owns its memory is None:

>>> x = np.array([1,2,3,4])
>>> x.base is None
True

Slicing creates a view, whose memory is shared with x:

>>> y = x[2:]
>>> y.base is x
True


15. How can you determine if the memory of a numpy array is writeable?

In [ ]:
a.flags.writeable # important

True

In [18]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

16. What does the `flags` attribute of a numpy array provide?

In [ ]:
# The flags attribute of a numpy array provides information about memory layout,
# writeability, and other properties of the array.

17. How can you check if a numpy array is a view of another array?


In [ ]:
# use .base attribute
# if it is not a view of another array, it returns 'None'
# it it is, it returns its base array.

18. Which attribute gives information about the memory layout of the array?


In [ ]:
# The flags attribute gives information about the memory layout of the array.
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

19. How can you determine the reference count of the array's data?


In [ ]:
a.refcount

AttributeError: ignored

In [6]:
# The refcount attribute determines the reference count of the array's data.
import sys # review

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Get the reference count of the array's data
ref_count = sys.getrefcount(arr.data) # review

print(f"The reference count of the array's data is {ref_count}")

The reference count of the array's data is 1


In [13]:
# Create a NumPy array
ndarray = np.array([1, 2, 3, 4, 5])

# Get the initial reference count
initial_ref_count = sys.getrefcount(ndarray)
print("Initial reference count:", initial_ref_count)

# Create an additional reference
new_reference = ndarray  # Creating a new reference to the same array

# Get the updated reference count
updated_ref_count = sys.getrefcount(ndarray)
print("Updated reference count:", updated_ref_count)

Initial reference count: 2
Updated reference count: 3


20. What does the `T` attribute of a numpy array represent?

In [ ]:
# The "T" attribute of a numpy array can be used to
# transpose the dimensions of a numpy array
# switch columns and rows
# i.e. the shape of a ndarray is (3, 4) -> (4, 3)

# The T attribute of a numpy array represents its transpose,
# which is equivalent to reversing the dimensions.