In [1]:
import numpy as np
import cluster

Exercise 10: (Section 10) K-means clustering, Algorithm 10.1

In [2]:
def kmeans(x,K,σ):

    # Start with random cluster means
    μ = np.random.normal(0.0,σ,K)

    # Initialization
    n = 0
    while True:

        # Update configuration
        Xnew = cluster.config(x,μ)

        # Update centroids
        μnew = cluster.means(x,Xnew)

        # Update centroids
        Fnew = cluster.Fobj(x,μnew,Xnew)
        print(f'\nIteration n={n}')
        print(f'Configuration X=\n{Xnew.T}')
        print(f'Centroids μ={μnew}')
        print(f'Objective F={Fnew}')

        # Convergence check
        if (n > 0) and np.array_equal(Xnew, X):
            return Xnew, μnew
        
        # Iteration
        n = n + 1
        X = Xnew
        μ = μnew

In [3]:
x = np.array([0.1,-0.3,2.6,1.1,2.3,-0.8,-6.2,-7.8,-1.5,-0.4])
print(f'Input data: x={x}')

Input data: x=[ 0.1 -0.3  2.6  1.1  2.3 -0.8 -6.2 -7.8 -1.5 -0.4]


In [13]:
K = 3
σ = 2.0
Xopt, μopt = kmeans(x,K,σ)
Fopt = cluster.Fobj(x,μopt,Xopt)
print(f'\nK-means clustering result: X*=\n{Xopt.T}, μ*={μopt}, F*={Fopt}')


Iteration n=0
Configuration X=
[[0. 0. 0. 0. 0. 1. 1. 1. 1. 0.]
 [1. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1.]]
Centroids μ=[-4.075  1.525 -0.35 ]
Objective F=39.72

Iteration n=1
Configuration X=
[[0. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 1. 0. 0. 1. 1.]]
Centroids μ=[-7.    2.   -0.58]
Objective F=4.007999999999999

Iteration n=2
Configuration X=
[[0. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 1. 0. 0. 1. 1.]]
Centroids μ=[-7.    2.   -0.58]
Objective F=4.007999999999999

K-means clustering result: X*=
[[0. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 1. 0. 0. 1. 1.]], μ*=[-7.    2.   -0.58], F*=4.007999999999999


Challenge: run multiple times with different initial conditions, select optimal clustering

In [14]:
K = 4
σ = 2.0
Xopt, μopt = kmeans(x,K,σ)
Fopt = cluster.Fobj(x,μopt,Xopt)
print(f'\nK-means clustering result: X*=\n{Xopt.T}, μ*={μopt}, F*={Fopt}')


Iteration n=0
Configuration X=
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 1. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Centroids μ=[-0.35   2.    -4.075  0.1  ]
Objective F=37.0125

Iteration n=1
Configuration X=
[[0. 1. 0. 0. 0. 1. 0. 0. 1. 1.]
 [0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Centroids μ=[-0.75  2.   -7.    0.1 ]
Objective F=3.4299999999999993

Iteration n=2
Configuration X=
[[0. 0. 0. 0. 0. 1. 0. 0. 1. 1.]
 [0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Centroids μ=[-0.9  2.  -7.  -0.1]
Objective F=3.2399999999999993

Iteration n=3
Configuration X=
[[0. 0. 0. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 1.]]
Centroids μ=[-1.15  2.   -7.   -0.2 ]
Objective F=2.9249999999999994

Iteration n=4
Configuration X=
[[0. 0. 0. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 1.

In [9]:
K = 2
σ = 2.0
Xopt, μopt = kmeans(x,K,σ)
Fopt = cluster.Fobj(x,μopt,Xopt)
print(f'\nK-means clustering result: X*=\n{Xopt.T}, μ*={μopt}, F*={Fopt}')


Iteration n=0
Configuration X=
[[0. 0. 0. 0. 0. 0. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1. 0. 0. 0. 1.]]
Centroids μ=[-5.16666667  0.65714286]
Objective F=32.58380952380953

Iteration n=1
Configuration X=
[[0. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 1. 0. 0. 1. 1.]]
Centroids μ=[-7.      0.3875]
Objective F=16.48875

Iteration n=2
Configuration X=
[[0. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 1. 0. 0. 1. 1.]]
Centroids μ=[-7.      0.3875]
Objective F=16.48875

K-means clustering result: X*=
[[0. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 1. 0. 0. 1. 1.]], μ*=[-7.      0.3875], F*=16.48875


In [15]:
K = 5
σ = 2.0
Xopt, μopt = kmeans(x,K,σ)
Fopt = cluster.Fobj(x,μopt,Xopt)
print(f'\nK-means clustering result: X*=\n{Xopt.T}, μ*={μopt}, F*={Fopt}')


Iteration n=0
Configuration X=
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 1.]]
Centroids μ=[-1.5 -0.8  2.  -7.  -0.2]
Objective F=2.6799999999999993

Iteration n=1
Configuration X=
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 1.]]
Centroids μ=[-1.5 -0.8  2.  -7.  -0.2]
Objective F=2.6799999999999993

K-means clustering result: X*=
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 1.]], μ*=[-1.5 -0.8  2.  -7.  -0.2], F*=2.6799999999999993


In [11]:
K = 1
σ = 2.0
Xopt, μopt = kmeans(x,K,σ)
Fopt = cluster.Fobj(x,μopt,Xopt)
print(f'\nK-means clustering result: X*=\n{Xopt.T}, μ*={μopt}, F*={Fopt}')


Iteration n=0
Configuration X=
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Centroids μ=[-1.09]
Objective F=103.80900000000001

Iteration n=1
Configuration X=
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Centroids μ=[-1.09]
Objective F=103.80900000000001

K-means clustering result: X*=
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]], μ*=[-1.09], F*=103.80900000000001


In [17]:
K = 6
σ = 2.0
Xopt, μopt = kmeans(x,K,σ)
Fopt = cluster.Fobj(x,μopt,Xopt)
print(f'\nK-means clustering result: X*=\n{Xopt.T}, μ*={μopt}, F*={Fopt}')


Iteration n=0
Configuration X=
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]]
Centroids μ=[-0.35 -7.    0.1  -1.5  -0.8   2.  ]
Objective F=2.544999999999999

Iteration n=1
Configuration X=
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]]
Centroids μ=[-0.35 -7.    0.1  -1.5  -0.8   2.  ]
Objective F=2.544999999999999

K-means clustering result: X*=
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]], μ*=[-0.35 -7.    0.1  -1.5  -0.8   2.  ], F*=2.544999999999999
