# Numpy Broadcasting Coding Lab Questions

### Coding Questions:

1. Given two arrays `a = np.array([1, 2, 3])` and `b = np.array([1, 2])`, demonstrate how broadcasting would work between these two arrays if you try to add them.

In [1]:
import numpy as np

In [12]:
# my answer - wrong
a = np.array([1, 2, 3])
b = np.array([1, 2])
b = b[:, np.newaxis]
a + b

array([[2, 3, 4],
       [3, 4, 5]])

In [3]:
# right answer
a = np.array([1, 2, 3])
b = np.array([1, 2])
try:
    result = a + b
    print(result)
except ValueError as e:
    print("operands could not be broadcast together with shapes (3,) (2,)")

operands could not be broadcast together with shapes (3,) (2,)


2. Create a 3x3 numpy array and broadcast addition with the vector `[1, 0, -1]`.

In [8]:
c = np.random.randint(0, 10, (3, 3))
vector = np.array([1, 0, -1])
print(c)
c + vector

[[6 3 8]
 [7 5 1]
 [5 5 9]]


array([[7, 3, 7],
       [8, 5, 0],
       [6, 5, 8]])

3. Given a 1-D array of `[1, 2, 3, 4]` and 2-D array of `[[1, 2, 3, 4], [5, 6, 7, 8]]`, perform element-wise multiplication using broadcasting.

In [9]:
e = np.array([1, 2, 3, 4])
f = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])
e * f

array([[ 1,  4,  9, 16],
       [ 5, 12, 21, 32]])

4. Create a 4x1 array and a 1x4 array and perform element-wise multiplication using broadcasting.

In [10]:
g = np.random.randint(1, 4, (4, 1))
h = np.random.randint(1, 4, (1, 4))
print(g, h)
g * h

[[1]
 [2]
 [1]
 [2]] [[3 3 1 1]]


array([[3, 3, 1, 1],
       [6, 6, 2, 2],
       [3, 3, 1, 1],
       [6, 6, 2, 2]])

5. Given a 3x3 matrix, broadcast subtraction using a 1-D array of `[1, 0, -1]`.

In [11]:
i = np.random.randint(1, 4, (3, 3))
j = np.array([1, 0, -1])
print(i)
i - j

[[2 1 2]
 [3 1 2]
 [1 3 1]]


array([[1, 1, 3],
       [2, 1, 3],
       [0, 3, 2]])

6. Create a 3-D numpy array of shape (3, 3, 3) and broadcast addition with a 1-D array of `[1, 2, 3]`.

In [15]:
k = np.random.randint(1, 4, (3, 3, 3))
l = np.array([1, 2, 3])
print(k)
k + l

[[[3 2 2]
  [3 2 3]
  [2 2 1]]

 [[1 1 3]
  [3 3 2]
  [1 2 2]]

 [[2 2 2]
  [3 2 1]
  [2 3 2]]]


array([[[4, 4, 5],
        [4, 4, 6],
        [3, 4, 4]],

       [[2, 3, 6],
        [4, 5, 5],
        [2, 4, 5]],

       [[3, 4, 5],
        [4, 4, 4],
        [3, 5, 5]]])

7. Given a 2-D array of shape (2, 3), broadcast multiplication with a 2-D array of shape (2, 1).

In [17]:
m = np.random.randint(1, 4, (2, 3))
n = np.random.randint(1, 4, (2, 1))
print(m)
print(n)
m * n

[[2 3 3]
 [3 2 2]]
[[3]
 [2]]


array([[6, 9, 9],
       [6, 4, 4]])

8. Create a 2-D array of shape (5, 3) and broadcast addition with a 1-D array of shape (3,).

In [19]:
o = np.random.randint(0, 10, (5, 3))
p = np.random.randint(0, 10, (3,))
print(o)
print(p)
o + p

[[3 2 6]
 [2 2 0]
 [6 7 9]
 [7 6 8]
 [8 5 2]]
[5 3 2]


array([[ 8,  5,  8],
       [ 7,  5,  2],
       [11, 10, 11],
       [12,  9, 10],
       [13,  8,  4]])

9. Given a 2-D array of shape (6, 3), broadcast subtraction with a 2-D array of shape (6, 1).

In [20]:
q = np.random.randint(0, 10, (6, 3))
r = np.random.randint(0, 10, (6, 1))
print(q)
print(r)
q - r

[[1 9 8]
 [1 5 6]
 [8 5 8]
 [9 9 5]
 [3 6 1]
 [2 1 9]]
[[8]
 [4]
 [8]
 [8]
 [2]
 [3]]


array([[-7,  1,  0],
       [-3,  1,  2],
       [ 0, -3,  0],
       [ 1,  1, -3],
       [ 1,  4, -1],
       [-1, -2,  6]])

10. Create a 3-D numpy array of shape (4, 3, 2) and broadcast multiplication with a 2-D array of shape (3, 2).

In [21]:
s = np.random.randint(0, 10, (4, 3, 2))
t = np.random.randint(0, 10, (3, 2))
print(s)
print(t)
s * t

[[[5 6]
  [8 4]
  [9 0]]

 [[9 1]
  [5 1]
  [9 8]]

 [[5 1]
  [9 6]
  [2 4]]

 [[3 9]
  [5 8]
  [2 6]]]
[[8 4]
 [5 7]
 [6 4]]


array([[[40, 24],
        [40, 28],
        [54,  0]],

       [[72,  4],
        [25,  7],
        [54, 32]],

       [[40,  4],
        [45, 42],
        [12, 16]],

       [[24, 36],
        [25, 56],
        [12, 24]]])

11. Given a 2-D array of shape (4, 4), broadcast division with a 1-D array of shape (4,).

In [22]:
u = np.random.randint(0, 10, (4, 4))
v = np.random.randint(0, 10, (4,))
print(u)
print(v)
u / v

[[1 1 8 4]
 [7 7 9 0]
 [3 8 7 4]
 [5 4 5 3]]
[2 5 5 1]


array([[0.5, 0.2, 1.6, 4. ],
       [3.5, 1.4, 1.8, 0. ],
       [1.5, 1.6, 1.4, 4. ],
       [2.5, 0.8, 1. , 3. ]])

12. Create a 2-D array of shape (3, 4) and broadcast addition with a 1-D array of shape (4,).

In [23]:
w = np.random.randint(0, 10, (3, 4))
x = np.random.randint(0, 10, (4,))
print(w)
print(x)
w + x

[[6 5 7 5]
 [2 6 8 0]
 [3 7 3 0]]
[2 6 5 0]


array([[ 8, 11, 12,  5],
       [ 4, 12, 13,  0],
       [ 5, 13,  8,  0]])

13. Given a 3-D array of shape (2, 4, 5), broadcast subtraction with a 2-D array of shape (4, 5).

In [26]:
y = np.random.randint(0, 10, (2, 4, 5))
z = np.random.randint(0, 10, (4, 5))
print('y\n', y)
print('z\n', z)
y - z

y
 [[[6 5 9 6 1]
  [2 3 3 8 1]
  [7 9 8 9 8]
  [3 0 3 2 2]]

 [[5 6 9 1 0]
  [1 7 5 5 9]
  [9 1 9 8 6]
  [8 3 3 0 8]]]
z
 [[0 9 7 8 9]
 [1 8 3 2 7]
 [5 9 3 4 6]
 [0 4 2 6 2]]


array([[[ 6, -4,  2, -2, -8],
        [ 1, -5,  0,  6, -6],
        [ 2,  0,  5,  5,  2],
        [ 3, -4,  1, -4,  0]],

       [[ 5, -3,  2, -7, -9],
        [ 0, -1,  2,  3,  2],
        [ 4, -8,  6,  4,  0],
        [ 8, -1,  1, -6,  6]]])

14. Create a 3-D numpy array of shape (5, 4, 3) and broadcast multiplication with a 2-D array of shape (4, 3).

In [28]:
a0 = np.random.randint(0, 10, (5, 4, 3))
a1 = np.random.randint(0, 10, (4, 3))
print(a0)
print(a1)
a0 * a1

[[[4 5 5]
  [9 1 9]
  [2 1 7]
  [4 3 3]]

 [[1 1 9]
  [3 5 6]
  [0 4 1]
  [0 1 1]]

 [[2 3 4]
  [8 9 1]
  [5 1 2]
  [9 2 5]]

 [[6 0 0]
  [2 0 6]
  [7 9 3]
  [0 7 8]]

 [[4 3 8]
  [7 1 0]
  [7 2 7]
  [6 5 8]]]
[[7 4 8]
 [5 8 4]
 [4 2 1]
 [1 2 3]]


array([[[28, 20, 40],
        [45,  8, 36],
        [ 8,  2,  7],
        [ 4,  6,  9]],

       [[ 7,  4, 72],
        [15, 40, 24],
        [ 0,  8,  1],
        [ 0,  2,  3]],

       [[14, 12, 32],
        [40, 72,  4],
        [20,  2,  2],
        [ 9,  4, 15]],

       [[42,  0,  0],
        [10,  0, 24],
        [28, 18,  3],
        [ 0, 14, 24]],

       [[28, 12, 64],
        [35,  8,  0],
        [28,  4,  7],
        [ 6, 10, 24]]])

15. Given a 2-D array of shape (3, 2), broadcast addition with a 1-D array of shape (2,).

In [29]:
a2 = np.random.randint(0, 10, (3, 2))
a3 = np.random.randint(0, 10, (2,))
print(a2)
print(a3)
a2 + a3

[[4 6]
 [1 4]
 [5 9]]
[8 2]


array([[12,  8],
       [ 9,  6],
       [13, 11]])

16. Create a 2-D array of shape (4, 5) and broadcast subtraction with a 1-D array of shape (5,).

In [30]:
a4 = np.random.randint(0, 10, (4, 5))
a5 = np.random.randint(0, 10, (5,))
print(a4)
print(a5)
a4 - a5

[[1 9 2 4 7]
 [2 2 4 8 8]
 [3 7 9 4 2]
 [4 6 9 4 3]]
[1 0 5 5 3]


array([[ 0,  9, -3, -1,  4],
       [ 1,  2, -1,  3,  5],
       [ 2,  7,  4, -1, -1],
       [ 3,  6,  4, -1,  0]])

17. Given a 3-D array of shape (3, 2, 4), broadcast multiplication with a 2-D array of shape (2, 4).

In [32]:
a6 = np.random.randint(0, 10, (3, 2, 4))
a7 = np.random.randint(0, 10, (2, 4))
print(a6)
print(a7)
a6 * a7

[[[0 9 7 3]
  [4 2 6 5]]

 [[5 4 8 5]
  [4 7 3 1]]

 [[8 3 3 3]
  [7 1 8 5]]]
[[7 7 5 0]
 [8 8 8 1]]


array([[[ 0, 63, 35,  0],
        [32, 16, 48,  5]],

       [[35, 28, 40,  0],
        [32, 56, 24,  1]],

       [[56, 21, 15,  0],
        [56,  8, 64,  5]]])

18. Create a 3-D numpy array of shape (2, 3, 4) and broadcast addition with a 2-D array of shape (3, 4).

In [33]:
a8 = np.random.randint(0, 10, (2, 3, 4))
a9 = np.random.randint(0, 10, (3, 4))
print(a8)
print(a9)
a8 + a9

[[[3 3 8 8]
  [0 0 2 0]
  [4 3 1 4]]

 [[5 9 0 1]
  [1 1 3 4]
  [3 0 2 3]]]
[[1 2 3 7]
 [4 3 1 3]
 [6 8 9 6]]


array([[[ 4,  5, 11, 15],
        [ 4,  3,  3,  3],
        [10, 11, 10, 10]],

       [[ 6, 11,  3,  8],
        [ 5,  4,  4,  7],
        [ 9,  8, 11,  9]]])

19. Given a 2-D array of shape (5, 4), broadcast subtraction with a 1-D array of shape (4,).

In [35]:
a10 = np.random.randint(0, 10, (5, 4))
a11 = np.random.randint(0, 10, (4,))
print(a10)
print(a11)
a10 - a11

[[4 5 9 0]
 [0 0 7 5]
 [7 1 5 9]
 [0 5 0 8]
 [2 7 5 9]]
[4 9 6 0]


array([[ 0, -4,  3,  0],
       [-4, -9,  1,  5],
       [ 3, -8, -1,  9],
       [-4, -4, -6,  8],
       [-2, -2, -1,  9]])

20. Create a 2-D array of shape (6, 5) and broadcast multiplication with a 1-D array of shape (5,).

In [36]:
a12 = np.random.randint(0, 10, (6, 5))
a13 = np.random.randint(0, 10, (5,))
print(a12)
print(a13)
a12 * a13

[[1 6 1 3 7]
 [1 8 8 3 2]
 [9 5 4 7 5]
 [9 8 1 6 0]
 [0 0 6 1 6]
 [3 8 6 1 5]]
[4 4 2 9 3]


array([[ 4, 24,  2, 27, 21],
       [ 4, 32, 16, 27,  6],
       [36, 20,  8, 63, 15],
       [36, 32,  2, 54,  0],
       [ 0,  0, 12,  9, 18],
       [12, 32, 12,  9, 15]])