# Solutions to NumPy Overview Coding Questions

In [ ]:
# Solution to Question 1
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Solution to Question 2
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Solution to Question 3
np.full(10, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [ ]:
# Solution to Question 4
np.arange(10, 31, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [ ]:
# Solution to Question 5
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Solution to Question 6
np.random.rand()

0.10267531183896239

In [ ]:
# Solution to Question 7
np.random.randn(25)

array([-0.32624994, -0.57827739,  1.40446268, -0.05057287, -0.46543304,
       -0.38227586,  1.08081882,  0.89254832,  0.0446762 ,  1.30369994,
        2.08263079,  0.76126231, -0.05683699, -0.13300668, -0.35716509,
        1.38462265,  0.80452595,  0.16264174,  0.62268722,  0.94149713,
       -0.52161868, -0.18309221,  1.36541971, -0.38049757, -1.07065765])

In [ ]:
# Solution to Question 8
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
# Solution to Question 9
Z = np.diag(1 + np.arange(4), k=-1)
Z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [ ]:
# Solution to Question 10
Z = np.random.random((5,5))
Z.min(), Z.max()

(0.03058858263447073, 0.9591868569027133)

In [ ]:
# Solution to Question 11
np.dot(np.random.random((5, 3)), np.random.random((3, 2)))

array([[0.52681224, 1.63654187],
       [0.71744534, 1.43122368],
       [0.36845942, 1.07417146],
       [0.57345608, 1.40502399],
       [0.96744977, 1.07516561]])

In [ ]:
# Solution to Question 12
Z = np.zeros((8,8), dtype=int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
# Solution to Question 13
np.sort(np.random.random(10))

array([0.06188513, 0.14242993, 0.19947751, 0.27126885, 0.29839852,
       0.31892904, 0.32995921, 0.77575953, 0.77740044, 0.95072546])

In [ ]:
# Solution to Question 14
np.sum(np.random.random((3,3)))

3.775303830673393

In [ ]:
# Solution to Question 15
np.std(np.arange(1, 11))

2.8722813232690143

In [ ]:
# Solution to Question 16
Z = np.random.random((3,3,3))
np.sum(Z)

14.472320753128189

In [ ]:
# Solution to Question 17
Z = np.random.random(30)
Z.mean()

0.4371836957927595

In [ ]:
# Solution to Question 18
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
Y

array([[-0.04640359, -0.29049272,  0.12200444, -0.13386601, -0.18858214,
         0.04218564,  0.1228433 ,  0.05124032, -0.04348241,  0.36455318],
       [-0.21392178,  0.24282895, -0.24475492,  0.31254471, -0.01184687,
         0.08709497, -0.34672874,  0.20781881,  0.4234338 , -0.45646893],
       [ 0.10413919, -0.45691603,  0.27156528,  0.03710528,  0.394055  ,
        -0.33112767,  0.17400179, -0.46628058,  0.05113604,  0.22232169],
       [-0.09067915,  0.21868729,  0.06232466, -0.10569645,  0.27877772,
         0.34284884, -0.49167984, -0.39175264, -0.12727697,  0.30444654],
       [-0.3617477 ,  0.24386111, -0.4662543 , -0.22639623, -0.02079544,
         0.43559998,  0.40095419, -0.18679093, -0.25320468,  0.43477401]])

In [ ]:
# Solution to Question 19
Z = np.random.random((5,5))
Z[Z[:,1].argsort()]

array([[0.7215365 , 0.07006948, 0.16756999, 0.82377494, 0.52317126],
       [0.88045906, 0.24848795, 0.9977606 , 0.5937056 , 0.98187946],
       [0.21536409, 0.32092411, 0.50949969, 0.8119316 , 0.61936151],
       [0.47938042, 0.33541009, 0.18818724, 0.47435596, 0.30738427],
       [0.47874866, 0.89071325, 0.76787406, 0.05011077, 0.99742568]])

In [ ]:
# Solution to Question 20
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y,X)
R, T

(array([0.36262133, 0.96904582, 0.87331555, 0.16824765, 1.13488579,
        0.96226507, 0.70383429, 0.24806185, 0.77139047, 0.77306164]),
 array([1.06734331, 0.14762109, 0.86180311, 0.21092229, 1.07670798,
        1.45783316, 0.31894287, 1.20595148, 1.41180141, 1.32406356]))

In [ ]:
# Solution to Question 21
Z = np.random.random((10,3))
np.amax(Z, axis=1)

array([0.8181566 , 0.43160203, 0.80465175, 0.97374154, 0.85934832,
       0.73879168, 0.87355211, 0.05166648, 0.38319085, 0.80656651])

In [ ]:
# Solution to Question 23
np.tile(np.arange(0, 5), (5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [ ]:
# Solution to Question 24
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [ ]:
# Solution to Question 25
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
equal

array([False,  True,  True,  True, False])

In [ ]:
# Solution to Question 26
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y,X)
R, T

(array([0.40920379, 1.21478748, 0.51356566, 0.95054557, 0.74087266,
        0.83587491, 0.89296803, 1.02663955, 1.34299003, 0.98927775]),
 array([1.50994264, 0.72906651, 1.33670266, 1.15632692, 0.1573376 ,
        1.48905926, 1.37413487, 0.41369869, 0.82135922, 1.2310488 ]))

In [ ]:
# Solution to Question 27
Z = np.random.random(1000000)
np.power(Z,3)
Z*Z*Z

array([3.67269192e-02, 2.51399091e-01, 6.14375073e-08, ...,
       2.27089951e-01, 3.60397773e-01, 4.83323658e-01])

In [ ]:
# Solution to Question 28
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
np.equal(A, B)

array([ True,  True,  True,  True,  True])

In [ ]:
# Solution to Question 29
A = np.array([1,2,3,4,5])
B = np.array([4,5,6,7,8])
np.intersect1d(A,B)

array([4, 5])

In [ ]:
# Solution to Question 30
city_5_q1 = temperatures[4, :3]
print("Temperatures for the first quarter for City 5:", city_5_q1)

NameError: name 'temperatures' is not defined

In NumPy arrays, indexing starts at 0. So, temperatures[4] accesses the 5th row (City 5), as the cities are in rows. The :3 slice selects the first three columns, corresponding to January to March. Hence, temperatures[4, :3] extracts the temperatures for the first quarter for City 5.

In [ ]:
# Solution to Question 31
cities_above_20_in_july = temperatures[:, 6] > 20
selected_cities = temperatures[cities_above_20_in_july]
print("Cities with average temperature above 20°C in July:\n", selected_cities)

NameError: name 'temperatures' is not defined

July corresponds to the 7th column in the array (index 6 as indexing starts at 0). The condition temperatures[:, 6] > 20 creates a boolean array where each entry is True if the corresponding city's July temperature is above 20°C, and False otherwise. This boolean array is then used to index the original temperatures array, extracting only those rows where the condition is True.

In [ ]:
# Answer to Question 32
city_3_cold_months = temperatures[2] < 15
city_8_temps_during_city_3_cold = temperatures[7, city_3_cold_months]
average_temp_city_8 = np.mean(city_8_temps_during_city_3_cold)
print("Average temperature for City 8 during City 3's cold months:", average_temp_city_8)


NameError: name 'temperatures' is not defined

Here, temperatures[2] < 15 creates a boolean array corresponding to City 3, where each entry is True if the temperature is below 15°C. This boolean array is then used to index the 8th row (City 8) but only for those months where City 3's temperature is below 15°C, as indicated by temperatures[7, city_3_cold_months]. The average of these temperatures for City 8 is then calculated with np.mean().
