# Numpy Ufuncs Coding Lab Questions

### Coding Questions:

1. Given two arrays `a = np.array([1, 2, 3, 4])` and `b = np.array([5, 6, 7, 8])`, use a Numpy ufunc to compute the element-wise addition of `a` and `b`.

In [2]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(a + b)
np.add(a, b)

[ 6  8 10 12]


array([ 6,  8, 10, 12])

2. Compute the square root of every element in the array `c = np.array([9, 16, 25, 36, 49])` using a Numpy ufunc.

In [3]:
c = np.array([9, 16, 25, 36, 49])

np.sqrt(c)

array([3., 4., 5., 6., 7.])

3. Given an array `d = np.array([-1, -2, 3, 4, -5])`, use a Numpy ufunc to compute the absolute value of each element in the array.

In [4]:
d = np.array([-1, -2, 3, 4, -5])

np.abs(d)

array([1, 2, 3, 4, 5])

4. Use a Numpy ufunc to compute the exponential value of each element in the array `e = np.array([0, 1, 2, 3])`.

In [5]:
e = np.array([0, 1, 2, 3])

np.exp(e)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

5. Given two arrays `f = np.array([1, 2, 3])` and `g = np.array([1, 0, 1])`, use a Numpy ufunc to compute the element-wise division of `f` by `g`. Handle any potential errors or warnings.

In [6]:
f = np.array([1, 2, 3])
g = np.array([1, 0, 1])

np.divide(f, g)

<ipython-input-6-5e5c3ae457a1>:4: RuntimeWarning: divide by zero encountered in divide
  np.divide(f, g)


array([ 1., inf,  3.])

6. Compute the natural logarithm of each element in the array `h = np.array([1, np.e, np.e**2])` using a Numpy ufunc.

In [7]:
h = np.array([1, np.e, np.e**2])

np.log(h)

array([0., 1., 2.])

7. Use a Numpy ufunc to compute the sine value of each element in the array `i = np.array([0, np.pi/2, np.pi])`.

In [8]:
i = np.array([0, np.pi/2, np.pi])

np.sin(i)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

8. Given an array `j = np.array([1, 2, 3, 4, 5])`, use a Numpy ufunc to compute the factorial of each element.

In [14]:
# speicial
j = np.array([1, 2, 3, 4, 5])
np.vectorize(np.math.factorial)(j)

array([  1,   2,   6,  24, 120])

9. Use a Numpy ufunc to compute the hyperbolic tangent of each element in the array `k = np.array([-1, 0, 1])`.

In [15]:
# pay attention here
k = np.array([-1, 0, 1])

np.tanh(k)

array([-0.76159416,  0.        ,  0.76159416])

10. Given two arrays `l = np.array([1, 2, 3])` and `m = np.array([1, 4, 9])`, use a Numpy ufunc to compute the element-wise maximum of the two arrays.

In [17]:
l = np.array([1, 2, 3])
m = np.array([1, 4, 9])
np.maximum(l, m)

array([1, 4, 9])

11. Use a Numpy ufunc to compute the base-2 logarithm of each element in the array `n = np.array([2, 4, 8, 16])`.

In [18]:
n = np.array([2, 4, 8, 16])
np.log2(n)

array([1., 2., 3., 4.])

12. Given an array `o = np.array([0.1, 0.2, 0.3, 0.4])`, use a Numpy ufunc to round each element to the nearest integer.

In [19]:
o = np.array([0.1, 0.2, 0.3, 0.4])
np.round(o)

array([0., 0., 0., 0.])

13. Compute the sign of each element in the array `p = np.array([-5, 0, 5])` using a Numpy ufunc.

In [20]:
p = np.array([-5, 0, 5])
np.sign(p)

array([-1,  0,  1])

14. Use a Numpy ufunc to compute the element-wise reciprocal of the array `q = np.array([1, 2, 0.5])`.

In [21]:
q = np.array([1, 2, 0.5])
np.reciprocal(q)

array([1. , 0.5, 2. ])

15. Given two arrays `r = np.array([1, 2, 3])` and `s = np.array([3, 2, 1])`, use a Numpy ufunc to check if elements of `r` are greater than elements of `s` element-wise.

In [22]:
r = np.array([1, 2, 3])
s = np.array([3, 2, 1])
np.greater(r, s)

array([False, False,  True])

16. Use a Numpy ufunc to compute the floor division by 1 of the array `t = np.array([1.1, 2.9, 3.5, 4.7])`.

In [24]:
t = np.array([1.1, 2.9, 3.5, 4.7])
np.floor_divide(t, 1)

array([1., 2., 3., 4.])

17. Compute the ceiling value of each element in the array `u = np.array([-1.1, -0.9, 0, 0.9, 1.1])` using a Numpy ufunc.

In [25]:
'''
The ceiling value, also known as the "ceiling function," rounds a number up to
the nearest integer that is greater than or equal to the original number.
In other words, it finds the smallest integer greater than or equal to the given number.
It's often denoted as ⌈x⌉.
'''
u = np.array([-1.1, -0.9, 0, 0.9, 1.1])
np.ceil(u)

array([-1., -0.,  0.,  1.,  2.])

18. Given an array `v = np.array([1, 2, 3, 4, 5])`, use a Numpy ufunc to compute the negative of each element.

In [26]:
 v = np.array([1, 2, 3, 4, 5])
 np.negative(v)

array([-1, -2, -3, -4, -5])

19. Use a Numpy ufunc to compute the element-wise remainder of the division of the array `w = np.array([10, 9, 8, 7, 6])` by 3.

In [27]:
w = np.array([10, 9, 8, 7, 6])
np.remainder(w, 3)

array([1, 0, 2, 1, 0])

20. Given two arrays `x = np.array([1, 2, 3, 4, 5])` and `y = np.array([5, 4, 3, 2, 1])`, use a Numpy ufunc to compute the element-wise power of `x` raised to `y`.

In [28]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([5, 4, 3, 2, 1])

np.power(x, y)

array([ 1, 16, 27, 16,  5])