# Numpy Fancy Indexing Coding Lab Questions

1. Create a 1D numpy array of 10 random integers between 0 and 100. Use fancy indexing to obtain the elements at indices 2, 5, and 7.

In [1]:
'''
Fancy indexing in NumPy is a technique that allows you to access and manipulate
elements in an array using arrays of indices or boolean masks. It provides a
powerful and flexible way to extract, modify, or rearrange elements from an array.
'''
import numpy as np

In [7]:
arr = np.random.randint(0, 101, 10)
print(arr)
ind = [2, 5, 7]
print([arr[2], arr[5], arr[7]])
arr[ind]

[69 12 13 95 71 74 51 39 36  2]
[13, 74, 39]


array([13, 74, 39])

2. Given a 2D numpy array of shape (5, 5), use fancy indexing to extract the diagonal elements.

In [24]:
arr = np.random.randint(0, 101, (5, 5))
print(arr)

# pay attention
ind = np.arange(5), np.arange(5)
print(ind)
print(arr[ind])

[[52 18 64  8  2]
 [65 15  8  6  3]
 [45 61 21 99 11]
 [ 9 61 51 99 24]
 [87 37  6 99 88]]
(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]))
[52 15 21 99 88]


In [25]:
ind_wrong = [np.arange(5), np.arange(5)]
print(ind_wrong)

print(arr[ind_wrong])

[array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4])]
[[[52 18 64  8  2]
  [65 15  8  6  3]
  [45 61 21 99 11]
  [ 9 61 51 99 24]
  [87 37  6 99 88]]

 [[52 18 64  8  2]
  [65 15  8  6  3]
  [45 61 21 99 11]
  [ 9 61 51 99 24]
  [87 37  6 99 88]]]


3. Create a 1D numpy array of 20 random integers. Use fancy indexing to replace all even numbers with the value -1.

In [26]:
arr = np.random.randint(0, 101, 20)
arr[arr % 2 == 0] = -1
arr

array([93, 63, -1, 89, -1, 75, -1, 69, -1, -1, 99, 13, -1, 51, -1, -1, -1,
       37, -1, -1])

4. Given a 2D numpy array, use fancy indexing to extract all rows where the first element is greater than 50.

In [30]:
arr = np.random.randint(0, 101, (4, 4))
print(arr)
arr[arr[:, 0] > 50]

[[ 28 100  51   9]
 [  1  81  67  64]
 [ 37  64   8  50]
 [ 85   6  46  42]]


array([[85,  6, 46, 42]])

5. Create a 1D numpy array of 15 elements. Use fancy indexing to extract every 3rd element starting from the first element.

In [35]:
arr = np.random.randint(0, 101, 15)
print(arr)
print(arr[np.arange(0, 14, 3)])
arr[::3]

[ 9 84  6 89 89 10 22 22 60 50 72 69 91 55 69]
[ 9 89 22 50 91]


array([ 9, 89, 22, 50, 91])

6. Given a 2D numpy array of shape (6, 6), use fancy indexing to extract the first, third, and fifth columns.

In [38]:
arr = np.random.randint(0, 101, (6, 6))
print(arr)
arr[:, (0, 2, 4)]

[[71 51 74 82  7 60]
 [86 73 62 11 41 64]
 [57 41 33 57 85 92]
 [93 73  5 24 30 80]
 [59  2 41 56 23 71]
 [29  2  2 83 44 90]]


array([[71, 74,  7],
       [86, 62, 41],
       [57, 33, 85],
       [93,  5, 30],
       [59, 41, 23],
       [29,  2, 44]])

7. Create a 1D numpy array of 10 elements. Use fancy indexing to reverse the order of elements.

In [40]:
arr = np.random.randint(0, 101, 10)
print(arr)
arr[::-1]

[17 77 45 47 92 56 12 24 76 64]


array([64, 76, 24, 12, 56, 92, 47, 45, 77, 17])

8. Given a 2D numpy array, use fancy indexing to extract all elements that are greater than 30 and less than 60.

In [45]:
arr = np.random.randint(0, 101, (3, 3))
print(arr)
arr[(arr > 30) & (arr < 60)]

[[ 4 32 98]
 [90 15 19]
 [92  6 68]]


array([32])

9. Create a 1D numpy array of 12 elements. Use fancy indexing to extract all prime numbers from the array.

In [47]:
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(np.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

arr = np.random.randint(0, 101, 12)
print(arr)
# pay attenthion
# np.vecorize(function)(np array)
np.vectorize(is_prime)(arr)

[98 44  4 74 92 83 86 85  8 39 95 79]


array([False, False, False, False, False,  True, False, False, False,
       False, False,  True])

10. Given a 2D numpy array of shape (4, 4), use fancy indexing to extract the elements from the last row and first column.

In [49]:
arr = np.random.randint(0, 101, (4, 4))
arr[(-1, 0)]

44

11. Create a 1D numpy array of 8 elements. Use fancy indexing to extract all elements that are multiples of 3.

In [51]:
arr = np.random.randint(0, 101, 8)
arr[arr % 3 == 0]

array([96, 18, 39])

12. Given a 2D numpy array, use fancy indexing to extract all rows where the sum of the row elements is greater than 100.

In [57]:
arr = np.random.randint(0, 50, (4, 4))
print(arr)

# Calculate the row sums
row_sums = np.sum(arr, axis=1)

# Create a boolean mask for rows where the sum is greater than 100
mask = (row_sums > 100)

# arr[np.sum(arr, axis=1) > 100]

arr[mask]

[[25  1 20 24]
 [ 6 11 35 19]
 [21 42 14 24]
 [43 42 46 19]]


array([[21, 42, 14, 24],
       [43, 42, 46, 19]])

13. Create a 1D numpy array of 10 random integers between 0 and 50. Use fancy indexing to extract all numbers that are even and greater than 20.

In [58]:
arr = np.random.randint(0, 51, 10)
arr[(arr % 2 == 0) & (arr > 20)]

array([40, 24, 38, 22])

14. Given a 2D numpy array of shape (3, 3), use fancy indexing to extract the second row and second column.

In [59]:
arr = np.random.randint(0, 50, (3, 3))
arr[1, 1]

9

15. Create a 1D numpy array of 7 elements. Use fancy indexing to extract the first, fourth, and seventh elements.

In [63]:
arr = np.random.randint(0, 50, 7)
print(arr)
arr[::3]

[32 37 41 32 49 29 38]


array([32, 32, 38])

16. Given a 2D numpy array, use fancy indexing to extract all elements that are less than the mean value of the array.

In [65]:
arr = np.random.randint(0, 50, (4, 4))
print(arr[arr < arr.mean()])
print(arr[arr < np.mean(arr)])

[25  7  1 26 10  5  4 16]
[25  7  1 26 10  5  4 16]


17. Create a 1D numpy array of 9 elements. Use fancy indexing to extract all numbers that are odd and less than 15.

In [66]:
arr = np.random.randint(0, 50, 9)
arr[(arr % 2 != 0) & (arr < 15)]

array([11,  3])

18. Given a 2D numpy array of shape (5, 4), use fancy indexing to extract the first two rows and last two columns.

In [68]:
arr = np.random.randint(0, 50, (5, 4))
print(arr)
arr[:2, -2:]

[[19 10 30  6]
 [ 9  6 33  4]
 [ 9 24 32 36]
 [29 17 31 33]
 [27  7 44 16]]


array([[30,  6],
       [33,  4]])

19. Create a 1D numpy array of 10 elements. Use fancy indexing to extract all numbers that are greater than the median value of the array.

In [72]:
arr = np.random.randint(0, 50, 10)
arr[arr > np.median(arr)]

array([34, 36, 33, 39])

20. Given a 2D numpy array, use fancy indexing to extract all columns where the maximum value of the column is less than 50.

In [81]:
arr = np.random.randint(0, 60, (4, 4))
print(arr)
arr[:, np.max(arr, axis=0) < 50]

[[48 46 16 36]
 [52  2 43 29]
 [19  9 40 53]
 [26  7 11 13]]


array([[46, 16],
       [ 2, 43],
       [ 9, 40],
       [ 7, 11]])