# Numpy Aggregate Functions Coding Lab Questions

1. Create a 1-D numpy array of 10 random integers and compute the sum of all its elements.

In [1]:
import numpy as np

a = np.random.randint(0, 10, 10)
print(a)
print(a.sum())
np.sum(a)

[9 5 9 7 2 7 3 4 3 0]
49


49

2. Given a 2-D numpy array of shape (5, 5), compute the minimum value of each row.

In [ ]:
b = np.arange(0, 25, 1)
b = b.reshape(5, 5)
print(b)
b.min(axis=1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([ 0,  5, 10, 15, 20])

3. Compute the cumulative sum of a 1-D numpy array of 10 elements.

In [ ]:
c = np.arange(0, 10, 1)
print(c)
c.cumsum()

[0 1 2 3 4 5 6 7 8 9]


array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

4. Find the mean value of a 2-D numpy array of shape (4, 4).

In [ ]:
d = np.arange(0, 16, 1).reshape(4, 4)
print(d)
print(d.mean())
np.mean(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
7.5


7.5

5. Compute the standard deviation of a 1-D numpy array of 20 elements.

In [ ]:
e = np.arange(0, 20, 1)
print(e.std())
np.std(e)

5.766281297335398


5.766281297335398

6. Given a 2-D numpy array of shape (3, 3), compute the maximum value of each column.

In [ ]:
f = np.arange(0, 9).reshape(3, 3)
print(f)
f.max(axis=0)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([6, 7, 8])

7. Compute the median of a 1-D numpy array of 15 elements.

In [ ]:
g = np.arange(0, 15, 1)
print(np.median(g))
g.median

7.0


AttributeError: ignored

8. Find the variance of a 2-D numpy array of shape (5, 3).

In [ ]:
h = np.arange(0, 15, 1).reshape(5, 3)
print(np.var(h))
h.var()

18.666666666666668


18.666666666666668

9. Compute the product of all elements in a 1-D numpy array of 10 elements.

In [ ]:
i = np.arange(1, 11, 1)
print(np.prod(i))
i.prod()

3628800


3628800

10. Given a 2-D numpy array of shape (6, 4), compute the cumulative product along each row.

In [ ]:
j = np.arange(0, 24, 1).reshape(6, 4)
print(j.cumprod(axis=1))
print(np.cumprod(j, axis=1))

[[     0      0      0      0]
 [     4     20    120    840]
 [     8     72    720   7920]
 [    12    156   2184  32760]
 [    16    272   4896  93024]
 [    20    420   9240 212520]]
[[     0      0      0      0]
 [     4     20    120    840]
 [     8     72    720   7920]
 [    12    156   2184  32760]
 [    16    272   4896  93024]
 [    20    420   9240 212520]]


In [ ]:
np.random.randint(1, 10, (6, 4))

array([[2, 2, 1, 4],
       [6, 6, 5, 7],
       [1, 4, 1, 2],
       [7, 9, 4, 8],
       [2, 3, 6, 1],
       [2, 7, 6, 8]])

11. Compute the 25th percentile of a 1-D numpy array of 50 elements.

In [ ]:
k = np.arange(0, 50, 1)
print(k)
print(np.percentile(k, 25))
# 12 + (0.25 * (13 - 12)) = 12 + 0.25 = 12.25

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
24.5


12. Find the 75th percentile of a 2-D numpy array of shape (7, 7).

In [ ]:
l = np.random.randint(1, 10, (7, 7))
print(l)
np.percentile(l, 75)

[[5 9 8 7 2 9 9]
 [4 9 6 2 3 7 6]
 [1 6 4 9 2 8 8]
 [1 7 9 8 4 3 4]
 [7 7 7 2 6 1 7]
 [3 7 2 3 9 8 6]
 [9 7 5 2 5 1 9]]


8.0

In [ ]:
np.percentile?

13. Compute the sum of all elements in a 2-D numpy array of shape (3, 3) along the diagonal.

In [ ]:
m = np.random.randint(1, 10, (3, 3))
print(m)
print(np.diagonal(m).sum())

diagonal_sum = np.trace(m)
diagonal_sum

[[1 6 9]
 [6 3 3]
 [8 1 4]]
8


8

14. Given a 1-D numpy array of 20 elements, compute the sum of its positive elements.

In [ ]:
n = np.random.randint(-10, 10, 20)
print(n)
sum = np.sum(n[n >= 0])
sum

[  1  -6   8   2 -10  -3  -7  -2 -10   7   5  -9  -2   2  -7 -10  -7  -8
   9  -7]


34

15. Compute the mean value of each column in a 2-D numpy array of shape (4, 5).

In [ ]:
o = np.random.randint(0, 10, (4, 5))
print(o)
np.sum(o, axis=0)

[[0 6 6 5 6]
 [0 5 5 4 0]
 [2 0 2 5 5]
 [1 7 8 4 7]]


array([ 3, 18, 21, 18, 18])

16. Find the minimum value of a 2-D numpy array of shape (5, 6) along the diagonal.

In [ ]:
p = np.random.randint(1, 10, (5, 6))
print(p)
np.min(np.diagonal(p))

[[9 3 2 1 5 4]
 [9 5 5 5 9 3]
 [8 2 2 1 6 1]
 [6 1 2 5 4 5]
 [9 9 4 9 6 2]]


2

17. Compute the standard deviation of each row in a 2-D numpy array of shape (3, 7).

In [ ]:
q = np.random.randint(1, 10, (3, 7))
print(q)
np.std(q, axis=1)

[[7 2 7 9 6 8 7]
 [1 3 3 6 6 9 3]
 [5 6 4 8 7 9 3]]


array([2.06031501, 2.49897938, 2.        ])

18. Given a 1-D numpy array of 30 elements, compute the difference between its maximum and minimum values.

In [ ]:
r = np.random.randint(1, 10, 30)
print(r)
max_min = r.max() - r.min()
max_min

[1 5 2 7 5 1 2 7 2 6 7 6 8 7 9 5 6 4 2 2 2 4 5 4 4 6 9 9 3 6]


8

19. Compute the product of all non-zero elements in a 1-D numpy array of 25 elements.

In [ ]:
s = np.random.randint(0, 10, 25)
np.prod(s[s != 0])

1120210560000000

20. Find the variance of each column in a 2-D numpy array of shape (8, 4).

In [ ]:
t = np.random.randint(0, 10, (8, 4))
print(np.var(t, axis=1))
print(np.var(t, axis=0))
# When doing calculation of a np.array, axis=0 means column

[ 1.1875  9.5     2.25   15.1875  6.5     6.6875  7.5     2.1875]
[6.734375 8.       8.734375 2.75    ]


In [3]:
eg = np.random.randint(0, 10, (8, 4))
print(eg)
print("Flip rows", np.flip(eg, axis=0))
print("Flip columns", np.flip(eg, axis=1))
# When reshaping a np.array, axis=0 means row

[[1 6 5 0]
 [3 5 7 7]
 [6 9 8 7]
 [5 8 7 6]
 [3 8 1 3]
 [7 9 0 0]
 [3 9 0 7]
 [4 9 2 4]]
Flip rows [[4 9 2 4]
 [3 9 0 7]
 [7 9 0 0]
 [3 8 1 3]
 [5 8 7 6]
 [6 9 8 7]
 [3 5 7 7]
 [1 6 5 0]]
Flip columns [[0 5 6 1]
 [7 7 5 3]
 [7 8 9 6]
 [6 7 8 5]
 [3 1 8 3]
 [0 0 9 7]
 [7 0 9 3]
 [4 2 9 4]]
