# Numpy Ufuncs Coding Lab Questions

### Coding Questions:

1. Given two arrays `a = np.array([1, 2, 3, 4])` and `b = np.array([5, 6, 7, 8])`, use a Numpy ufunc to compute the element-wise addition of `a` and `b`.

2. Compute the square root of every element in the array `c = np.array([9, 16, 25, 36, 49])` using a Numpy ufunc.

3. Given an array `d = np.array([-1, -2, 3, 4, -5])`, use a Numpy ufunc to compute the absolute value of each element in the array.

4. Use a Numpy ufunc to compute the exponential value of each element in the array `e = np.array([0, 1, 2, 3])`.

5. Given two arrays `f = np.array([1, 2, 3])` and `g = np.array([1, 0, 1])`, use a Numpy ufunc to compute the element-wise division of `f` by `g`. Handle any potential errors or warnings.

6. Compute the natural logarithm of each element in the array `h = np.array([1, np.e, np.e**2])` using a Numpy ufunc.

7. Use a Numpy ufunc to compute the sine value of each element in the array `i = np.array([0, np.pi/2, np.pi])`.

8. Given an array `j = np.array([1, 2, 3, 4, 5])`, use a Numpy ufunc to compute the factorial of each element. Hint: look at the documentation for the vectorize function.

9. Use a Numpy ufunc to compute the hyperbolic tangent of each element in the array `k = np.array([-1, 0, 1])`.

10. Given two arrays `l = np.array([1, 2, 3])` and `m = np.array([1, 4, 9])`, use a Numpy ufunc to compute the element-wise maximum of the two arrays.

11. Use a Numpy ufunc to compute the base-2 logarithm of each element in the array `n = np.array([2, 4, 8, 16])`.

12. Given an array `o = np.array([0.1, 0.2, 0.3, 0.4])`, use a Numpy ufunc to round each element to the nearest integer.

13. Compute the sign of each element in the array `p = np.array([-5, 0, 5])` using a Numpy ufunc.

14. Use a Numpy ufunc to compute the element-wise reciprocal of the array `q = np.array([1, 2, 0.5])`.

15. Given two arrays `r = np.array([1, 2, 3])` and `s = np.array([3, 2, 1])`, use a Numpy ufunc to check if elements of `r` are greater than elements of `s` element-wise.

16. Use a Numpy ufunc to compute the floor division of the array `t = np.array([1.1, 2.9, 3.5, 4.7])`.

17. Compute the ceiling value of each element in the array `u = np.array([-1.1, -0.9, 0, 0.9, 1.1])` using a Numpy ufunc.

18. Given an array `v = np.array([1, 2, 3, 4, 5])`, use a Numpy ufunc to compute the negative of each element.

19. Use a Numpy ufunc to compute the element-wise remainder of the division of the array `w = np.array([10, 9, 8, 7, 6])` by 3.

20. Given two arrays `x = np.array([1, 2, 3, 4, 5])` and `y = np.array([5, 4, 3, 2, 1])`, use a Numpy ufunc to compute the element-wise power of `x` raised to `y`.

# Solutions

In [ ]:
import numpy as np

In [ ]:
# Solution to Question 1
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
result_1 = np.add(a, b)
result_1

array([ 6,  8, 10, 12])

In [ ]:
# Solution to Question 2
c = np.array([9, 16, 25, 36, 49])
result_2 = np.sqrt(c)
result_2

array([3., 4., 5., 6., 7.])

In [ ]:
# Solution to Question 3
d = np.array([-1, -2, 3, 4, -5])
result_3 = np.abs(d)
result_3

array([1, 2, 3, 4, 5])

In [ ]:
# Solution to Question 4
e = np.array([0, 1, 2, 3])
result_4 = np.exp(e)
result_4

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [ ]:
# Solution to Question 5
f = np.array([1, 2, 3])
g = np.array([1, 0, 1])
result_5 = np.divide(f, g, where=g!=0)
result_5

array([1.        , 0.55950035, 3.        ])

In [ ]:
# Solution to Question 6
h = np.array([1, np.e, np.e**2])
result_6 = np.log(h)
result_6

array([0., 1., 2.])

In [ ]:
# Solution to Question 7
i = np.array([0, np.pi/2, np.pi])
result_7 = np.sin(i)
result_7

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [ ]:
# Solution to Question 8
j = np.array([1, 2, 3, 4, 5])
result_8 = np.vectorize(np.math.factorial)(j)
result_8

array([  1,   2,   6,  24, 120])

In [ ]:
# Solution to Question 9
k = np.array([-1, 0, 1])
result_9 = np.tanh(k)
result_9

array([-0.76159416,  0.        ,  0.76159416])

In [ ]:
# Solution to Question 10
l = np.array([1, 2, 3])
m = np.array([3, 2, 1])
result_10 = np.maximum(l, m)
result_10

array([3, 2, 3])

In [ ]:
# Solution to Question 11
n = np.array([2, 4, 8, 16])
result_11 = np.log2(n)
result_11

array([1., 2., 3., 4.])

In [ ]:
# Solution to Question 12
o = np.array([0.1, 0.2, 0.3, 0.4])
result_12 = np.round(o)
result_12

array([0., 0., 0., 0.])

In [ ]:
# Solution to Question 13
p = np.array([-5, 0, 5])
result_13 = np.sign(p)
result_13

array([-1,  0,  1])

In [ ]:
# Solution to Question 14
q = np.array([1, 2, 0.5])
result_14 = np.reciprocal(q)
result_14

/var/folders/8n/bj3r8xcx6xq3gs8dwyknqt3h0000gn/T/ipykernel_12289/2068333281.py:3: RuntimeWarning: invalid value encountered in reciprocal
  result_14 = np.reciprocal(q)


array([1. , 0.5, 2. ])

In [ ]:
# Solution to Question 15
r = np.array([1, 2, 3])
s = np.array([3, 2, 1])
result_15 = r > s
result_15

array([False, False,  True])

In [ ]:
# Solution to Question 16
t = np.array([1.1, 2.9, 3.5, 4.7])
result_16 = np.floor_divide(t, 1)
result_16

array([1., 2., 3., 4.])

In [ ]:
# Solution to Question 17
u = np.array([-1.1, -0.9, 0, 0.9, 1.1])
result_17 = np.ceil(u)
result_17

array([-1., -0.,  0.,  1.,  2.])

In [ ]:
# Solution to Question 18
v = np.array([1, 2, 3, 4, 5])
result_18 = np.negative(v)
result_18

array([-1, -2, -3, -4, -5])

In [ ]:
# Solution to Question 19
w = np.array([10, 9, 8, 7, 6])
result_19 = np.remainder(w, 3)
result_19

array([1, 0, 2, 1, 0])

In [ ]:
# Solution to Question 20
x = np.array([1, 2, 3, 4, 5])
y = np.array([5, 4, 3, 2, 1])
result_20 = np.power(x, y)
result_20

array([ 1, 16, 27, 16,  5])