# Numpy Comparisons, Masks, and Boolean Logic Coding Lab Questions

1. Create a 1-D numpy array of 10 random integers. Identify and print all the even numbers from the array.

In [1]:
import numpy as np

In [4]:
a = np.random.randint(0, 10, 10)
print(a)
a[a % 2 == 0]

[2 0 7 0 8 7 5 6 5 7]


array([2, 0, 0, 8, 6])

2. Given a 2-D numpy array of shape (5, 5), identify and print all the elements greater than 50.

In [5]:
b = np.random.randint(0, 100, (5, 5))
b[b > 50]

array([66, 55, 58, 83, 94, 76, 74, 53, 82, 86])

3. Create a 1-D numpy array of 10 elements. Use boolean masking to replace all odd numbers with -1.

In [7]:
c = np.random.randint(0, 10, 10)
c[c % 2 != 0] = -1
c

array([-1,  2,  4,  4, -1, -1,  6,  0,  6, -1])

4. Given a 2-D numpy array of shape (4, 4), identify and print the positions (indices) of elements less than 10.

In [15]:
d = np.random.randint(0, 20, (4, 4))
print(d)
print(d[d < 10])
np.argwhere(d < 10)

[[ 4 15 13 18]
 [10  7 14  7]
 [ 7 10 12 12]
 [ 5  9 11 19]]
[4 7 7 7 5 9]


array([[0, 0],
       [1, 1],
       [1, 3],
       [2, 0],
       [3, 0],
       [3, 1]])

5. Create a 1-D numpy array of 20 elements. Count the number of elements that are either greater than 40 or less than 20.

In [25]:
e = np.random.randint(0, 60, 20)
print(e[e > 40])
print(e[e < 20])
np.sum((e > 40) | (e < 20))

[44 50 41 59 41 51 52]
[14 14]


9

6. Given a 2-D numpy array of shape (3, 3), check if any of the rows contain an element greater than 30.

In [34]:
f = np.random.randint(0, 60, (3, 3))
print(f)
np.any(f > 30, axis=1)

[[ 4 57 57]
 [14 19 40]
 [43 20 36]]


array([ True,  True,  True])

7. Create a 1-D numpy array of 15 elements. Use boolean logic to identify and print all elements that are not divisible by 3.

In [36]:
g = np.random.randint(0, 60, 15)
g[g % 3 != 0]

array([11, 49, 23, 59, 40, 58, 19, 58,  2, 13, 41])

8. Given a 2-D numpy array of shape (5, 3), identify and print all columns that have a mean value greater than 25.

In [39]:
h = np.random.randint(0, 60, (5, 3))
print(h)
np.mean(h, axis=0) > 25

[[49 31 51]
 [51  9  5]
 [28  7 35]
 [56 12 44]
 [59  8 42]]


array([ True, False,  True])

9. Create a 1-D numpy array of 10 elements. Identify the positions (indices) of all elements that are either less than 5 or greater than 8.

In [44]:
i = np.random.randint(0, 20, 10)
print(i)
np.argwhere((i > 8) | (i < 5))

[19  6 16 15  3 19 17  2  5 18]


array([[0],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [9]])

10. Given a 2-D numpy array of shape (6, 4), check if all elements in the array are positive.

In [48]:
j = np.random.randint(-100, 100, (6, 4))
print(j)
np.all(j > 0)

[[-93 -25  34  10]
 [-45 -39  34 -93]
 [  0  72  89  12]
 [-25  66  13 -95]
 [-67  -1 -59 -14]
 [-51 -54 -99 -10]]


False

11. Create a 1-D numpy array of 50 elements. Count the number of elements that are divisible by 7 and greater than 30.

In [50]:
k = np.random.randint(0, 100, 50)
print(k[k % 7 ==0])
print(k[k > 30])
np.sum((k % 7 ==0) & (k > 30))

[ 0 98 56 98  7 84 14 84 70]
[57 31 33 75 97 89 82 32 90 64 98 73 56 97 99 32 50 67 98 76 46 46 65 66
 84 45 86 84 85 68 65 33 70 50]


6

12. Given a 2-D numpy array of shape (7, 7), identify and print the positions (indices) of elements that are less than 10 or greater than 60.

In [55]:
l = np.random.randint(0, 100, (7, 7))
print(l[l < 10])
print(l[l > 60])
np.argwhere((l < 10) | (l > 60))

[0 4 3 6 6]
[82 90 75 98 73 70 85 94 86 67 93 95 81 93 76]


array([[0, 0],
       [0, 1],
       [0, 3],
       [0, 6],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 4],
       [1, 6],
       [2, 1],
       [2, 3],
       [3, 6],
       [4, 2],
       [4, 6],
       [5, 1],
       [5, 5],
       [5, 6],
       [6, 3],
       [6, 4],
       [6, 5]])

13. Create a 1-D numpy array of 20 elements. Use boolean masking to replace all elements less than 10 with the value 0 and all elements greater than 50 with the value 100.

In [56]:
m = np.random.randint(0, 100, 20)
m[m < 10] = 0
m[m > 50] = 100
m

array([100,  15, 100,  19,  11, 100, 100,  34, 100, 100,  25,   0, 100,
         0, 100, 100,   0,  43,  33,   0])

14. Given a 2-D numpy array of shape (5, 5), identify and print all the elements that are between 20 and 40 (both inclusive).

In [61]:
m = np.random.randint(0, 100, (5, 5))
m[(m >= 20) & (m <= 40)]

array([30, 25, 39, 37, 29, 30])

15. Create a 1-D numpy array of 25 elements. Identify and print the positions (indices) of all elements that are divisible by 5 or divisible by 7.

In [62]:
m = np.random.randint(0, 100, 25)
np.argwhere((m % 5 == 0) | (m % 7 ==0))

array([[ 0],
       [ 1],
       [ 2],
       [ 4],
       [15],
       [18],
       [21],
       [22]])

16. Given a 2-D numpy array of shape (5, 6), check if any of the columns contain an element less than 5.

In [66]:
arr = np.random.randint(0, 100, (5, 6))
np.any(arr < 5, axis=0)

array([False,  True,  True, False, False, False])

17. Create a 1-D numpy array of 30 elements. Use boolean logic to identify and print all elements that are not between 10 and 30 (both exclusive).

In [67]:
arr = np.random.randint(0, 100, 30)
arr[(arr > 30) | (arr < 10)]

array([71, 60, 58, 39, 66, 80,  8, 82,  6, 68, 82, 96, 91, 36, 88,  0,  2,
       31, 93, 37, 60, 45, 50, 53, 43,  7])

18. Given a 2-D numpy array of shape (4, 4), identify and print the positions (indices) of elements that are equal to 25.

In [70]:
arr = np.random.randint(0, 100, (4, 4))
np.argwhere((arr == 25))

array([[0, 3]])

19. Create a 1-D numpy array of 25 elements. Identify and print all elements that are either even or greater than 40.

In [71]:
arr = np.random.randint(0, 100, 25)
arr[(arr % 2 ==0) | (arr > 40)]

array([76, 65, 95, 45, 89, 60, 67, 83, 89, 61, 78, 73, 51, 77, 64, 16, 58,
       67, 88, 52, 45, 44, 75, 18])

20. Given a 2-D numpy array of shape (6, 5), check if all rows contain at least one element greater than 50.

In [72]:
arr = np.random.randint(0, 100, (6, 5))
np.any((arr > 50), axis=1)

array([False,  True,  True,  True,  True, False])